FROM {{ARG_FROM}}

ENV BIND_ADDR=":4430" \
    PROD="1"

WORKDIR /home/go/src/hkjn.me/hkjnweb

USER root
RUN apk add --no-cache musl-dev
USER go

COPY ["*.go", "./"]
COPY ["blog/", "./blog/"]
COPY ["cmd/", "./cmd/"]
COPY ["pages/", "./pages/"]
COPY ["static/", "./static/"]
COPY ["tmpl/", "./tmpl/"]
COPY ["vendor", "./vendor/"]

RUN go test && \
    go vet && \
    go install hkjn.me/hkjnweb/cmd/server

ENTRYPOINT ["server"]
CMD ["-alsologtostderr"]
